# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_web', '0002_document_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='topics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
